//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERINFO
    {
        public System.Guid GUID { get; set; }
        public string CUSTOMERPHONE { get; set; }
        public string CUSTOMERPWD { get; set; }
        public string SHOPNAME { get; set; }
        public string SHOPLEADERNAME { get; set; }
        public string CITY { get; set; }
        public string ADDR { get; set; }
        public string INVITECODE { get; set; }
        public string BUSINESSLICENSE { get; set; }
        public string SALESMANNAME { get; set; }
        public Nullable<System.Guid> SALESMANID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public int ISDELETED { get; set; }
        public string DELETEUSER { get; set; }
        public Nullable<System.DateTime> DELETETIME { get; set; }
        public Nullable<System.Guid> CITYID { get; set; }
    }
}
