//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jincaiEntities : DbContext
    {
        public jincaiEntities()
            : base("name=jincaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ORDERDETAIL> ORDERDETAIL { get; set; }
        public DbSet<STOREINFO> STOREINFO { get; set; }
        public DbSet<VEGETABLESINFO> VEGETABLESINFO { get; set; }
        public DbSet<VEGETABLESTYPE> VEGETABLESTYPE { get; set; }
        public DbSet<VEGETABLESPARENTTYPE> VEGETABLESPARENTTYPE { get; set; }
        public DbSet<CUSTOMERINFO> CUSTOMERINFO { get; set; }
        public DbSet<SYS_USER> SYS_USER { get; set; }
        public DbSet<SYS_DATADIC> SYS_DATADIC { get; set; }
        public DbSet<SYS_DATADICLIST> SYS_DATADICLIST { get; set; }
        public DbSet<BUSINESSAREA> BUSINESSAREA { get; set; }
        public DbSet<VEGETABLESNAMEBASE> VEGETABLESNAMEBASE { get; set; }
        public DbSet<ORDERLIST> ORDERLIST { get; set; }
        public DbSet<VEGETABLESINFOCHANGELOG> VEGETABLESINFOCHANGELOG { get; set; }
    }
}
