//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERDETAIL
    {
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> ORDERID { get; set; }
        public Nullable<System.Guid> CUSTOMERID { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string VEGETABLESNAME { get; set; }
        public string VEGETABLESDES { get; set; }
        public string BIGUNIT { get; set; }
        public string SMALLUNIT { get; set; }
        public Nullable<int> PACKRULE { get; set; }
        public Nullable<System.Guid> TYPEID { get; set; }
        public string TYPENAME { get; set; }
        public string BIGIMAGEURL { get; set; }
        public string SMALLIMAGEURL { get; set; }
        public Nullable<System.Guid> STOREID { get; set; }
        public string STORENAME { get; set; }
        public Nullable<System.Guid> AREAID { get; set; }
        public string AREANAME { get; set; }
        public Nullable<decimal> BIGPRICE { get; set; }
        public Nullable<decimal> SMALLPRICE { get; set; }
        public Nullable<System.Guid> VEGETABLESID { get; set; }
        public Nullable<int> BUYNUM { get; set; }
        public Nullable<decimal> TOTALCASH { get; set; }
    }
}
