//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERLIST
    {
        public System.Guid GUID { get; set; }
        public string ORDERCODE { get; set; }
        public string CUSTOMERSHOPNAME { get; set; }
        public Nullable<decimal> ORDERTOTALMONEY { get; set; }
        public string ORDERSTATUS { get; set; }
        public Nullable<System.DateTime> ORDERTIME { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.Guid> CUSTOMERID { get; set; }
        public string STORENAME { get; set; }
        public Nullable<System.Guid> STOREID { get; set; }
        public string AREANAME { get; set; }
        public Nullable<System.Guid> AREAID { get; set; }
        public string ORDERSTATUSNAME { get; set; }
    }
}
