//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_DATADIC
    {
        public int DICID { get; set; }
        public string DICNAME { get; set; }
        public string ABBRE { get; set; }
        public string REMARK { get; set; }
        public string DICLISTNAME { get; set; }
        public string UNIQUEFLAG { get; set; }
        public Nullable<int> SEQUENCE { get; set; }
        public string IP { get; set; }
        public Nullable<int> USERID { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<System.DateTime> OPERATEDATE { get; set; }
        public string ISDELETED { get; set; }
        public string DELETEUSER { get; set; }
        public Nullable<System.DateTime> DELETEDATE { get; set; }
        public string ISDISABLED { get; set; }
        public Nullable<System.DateTime> DISABLEDDATE { get; set; }
        public string DISABLEDUSER { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public string SUBIDS { get; set; }
        public string SUBNAMES { get; set; }
        public string ISDEFAULT { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDATE { get; set; }
        public string LASTUPDATEUSER { get; set; }
        public System.Guid GUID { get; set; }
    }
}
