//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_DATADICLIST
    {
        public string DATANAME { get; set; }
        public string UNIQUEFLAG { get; set; }
        public string ISTREE { get; set; }
        public int SEQUENCE { get; set; }
        public string PARENTCODE { get; set; }
        public System.Guid GUID { get; set; }
    }
}
